#!/bin/bash -eu

#################################################
# Create all the relevant symlinks for file
# in this repo
#################################################


# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # the directory this file is in
cd $SCRIPT_DIR



#################################################
# Files from home
#################################################
link_file_from_home() {
	local fullname=$1
	local file_dir=$(dirname "$fullname")
	local file_name=$(basename "$fullname")
	mkdir -p "$HOME/$file_dir"
	ln -s -f "$SCRIPT_DIR/files_from_home/$fullname" "$HOME/$file_dir/$file_name"
	echo ln -s -f "$SCRIPT_DIR/files_from_home/$fullname" "$HOME/$file_dir/$file_name"
}

link_files_from_home() {
	cd files_from_home
	find . -name '*' -type f | while read fname; do
  		link_file_from_home $fname
	done
	cd $SCRIPT_DIR
}

link_files_from_home


#################################################
# Files from root
#################################################

link_file_from_root() {
	local fullname=$1
	local file_dir=$(dirname "$fullname")
	local file_name=$(basename "$fullname")
	sudo mkdir -p "/$file_dir"
	sudo ln -s -f "$SCRIPT_DIR/files_from_root/$fullname" "/$file_dir/$file_name"
	echo sudo ln -s -f "$SCRIPT_DIR/files_from_root/$fullname" "/$file_dir/$file_name"
}

link_files_from_root() {
	cd files_from_root
	find . -name '*' -type f | while read fname; do
  		link_file_from_root $fname
	done
	cd $SCRIPT_DIR
}

link_files_from_root


#################################################
# Directories
#################################################
set -x

ln -sf "$SCRIPT_DIR/directories/PyCharm50/" ~/Library/Preferences/
ln -sf "$SCRIPT_DIR/directories/Sublime Text 3/Packages" "$HOME/Library/Application Support/Sublime Text 3/"
ln -sf "$SCRIPT_DIR/directories/Sublime Text 3/Installed Packages" "$HOME/Library/Application Support/Sublime Text 3/"


#################################################
# Other links
#################################################
ln -s -f $SCRIPT_DIR/files_other/prompt_kale_setup $HOME/.zprezto/modules/prompt/functions/prompt_kale_setup



